using UnityEngine;

public class EnglishChannelMap : Map
{
    public HexCoordinates[] waterCoords =
    {
        new HexCoordinates(0, 3),
        new HexCoordinates(1, 3),
        new HexCoordinates(2, 3),

        new HexCoordinates(0, 4),
        new HexCoordinates(1, 4),
        new HexCoordinates(2, 4),

        new HexCoordinates(-2, 5),
        new HexCoordinates(-1, 5),
        new HexCoordinates(0, 5),
        new HexCoordinates(1, 5),
        new HexCoordinates(2, 5),

        new HexCoordinates(-3, 6),
        new HexCoordinates(-2, 6),
        new HexCoordinates(-1, 6),
        new HexCoordinates(0, 6),
        new HexCoordinates(1, 6),
        new HexCoordinates(2, 6),
        new HexCoordinates(3, 6),

        new HexCoordinates(-3, 7),
        new HexCoordinates(-2, 7),
        new HexCoordinates(-1, 7),
        new HexCoordinates(0, 7),
        new HexCoordinates(1, 7),
        new HexCoordinates(2, 7),
        new HexCoordinates(3, 7),

        new HexCoordinates(-4, 8),
        new HexCoordinates(-3, 8),
        new HexCoordinates(-2, 8),
        new HexCoordinates(-1, 8),
        new HexCoordinates(0, 8),
        new HexCoordinates(1, 8),
        new HexCoordinates(2, 8),

        new HexCoordinates(-4, 9),
        new HexCoordinates(-3, 9),
        new HexCoordinates(-2, 9),
        new HexCoordinates(-1, 9),
        new HexCoordinates(0, 9),
        new HexCoordinates(1, 9),
        new HexCoordinates(2, 9),

        new HexCoordinates(0, 10),
        new HexCoordinates(1, 10),

        new HexCoordinates(1, 11),
        new HexCoordinates(2, 11),

        new HexCoordinates(1, 12),
        new HexCoordinates(2, 12),
        new HexCoordinates(3, 12),

        new HexCoordinates(-2, 13),
        new HexCoordinates(-1, 13),
        new HexCoordinates(0, 13),
        new HexCoordinates(1, 13),
        new HexCoordinates(2, 13),
        new HexCoordinates(3, 13),
        new HexCoordinates(4, 13),

        new HexCoordinates(-1, 14),
        new HexCoordinates(0, 14),
        new HexCoordinates(1, 14),
        new HexCoordinates(2, 14),
        new HexCoordinates(3, 14),
        new HexCoordinates(4, 14),

        new HexCoordinates(-1, 15),
        new HexCoordinates(0, 15),
        new HexCoordinates(1, 15),
        new HexCoordinates(2, 15),
        new HexCoordinates(3, 15),
        new HexCoordinates(4, 15),

        new HexCoordinates(-1, 16),
        new HexCoordinates(0, 16),
        new HexCoordinates(1, 16),
        new HexCoordinates(2, 16),
        new HexCoordinates(3, 16),
        new HexCoordinates(4, 16),

        new HexCoordinates(-1, 17),
        new HexCoordinates(0, 17),
        new HexCoordinates(1, 17),
        new HexCoordinates(2, 17),
        new HexCoordinates(3, 17),

        new HexCoordinates(-2, 18),
        new HexCoordinates(-1, 18),
        new HexCoordinates(0, 18),
        new HexCoordinates(1, 18),
        new HexCoordinates(2, 18),
        new HexCoordinates(3, 18),

        new HexCoordinates(-2, 19),
        new HexCoordinates(-1, 19),
        new HexCoordinates(0, 19),
        new HexCoordinates(1, 19),
        new HexCoordinates(2, 19),
        new HexCoordinates(3, 19),

        new HexCoordinates(-7, 20),
        new HexCoordinates(-6, 20),
        new HexCoordinates(-3, 20),
        new HexCoordinates(-2, 20),
        new HexCoordinates(-1, 20),
        new HexCoordinates(0, 20),
        new HexCoordinates(1, 20),
        new HexCoordinates(2, 20),
        new HexCoordinates(4, 20),

        new HexCoordinates(-7, 21),
        new HexCoordinates(-6, 21),
        new HexCoordinates(-5, 21),
        new HexCoordinates(-4, 21),
        new HexCoordinates(-3, 21),
        new HexCoordinates(-2, 21),
        new HexCoordinates(-1, 21),
        new HexCoordinates(0, 21),
        new HexCoordinates(1, 21),
        new HexCoordinates(2, 21),
        new HexCoordinates(4, 21),

        new HexCoordinates(-7, 22),
        new HexCoordinates(-6, 22),
        new HexCoordinates(-5, 22),
        new HexCoordinates(-4, 22),
        new HexCoordinates(-3, 22),
        new HexCoordinates(-2, 22),
        new HexCoordinates(-1, 22),
        new HexCoordinates(0, 22),
        new HexCoordinates(1, 22),
        new HexCoordinates(2, 22),
        new HexCoordinates(3, 22),

        new HexCoordinates(-7, 23),
        new HexCoordinates(-6, 23),
        new HexCoordinates(-5, 23),
        new HexCoordinates(-4, 23),
        new HexCoordinates(-3, 23),
        new HexCoordinates(-2, 23),
        new HexCoordinates(-1, 23),
        new HexCoordinates(0, 23),
        new HexCoordinates(1, 23),
        new HexCoordinates(2, 23), 
        
        new HexCoordinates(-8, 24),
        new HexCoordinates(-7, 24),
        new HexCoordinates(-6, 24),
        new HexCoordinates(-5, 24),
        new HexCoordinates(-4, 24),
        new HexCoordinates(-3, 24),
        new HexCoordinates(-2, 24),
        new HexCoordinates(-1, 24),
        new HexCoordinates(0, 24),
        new HexCoordinates(1, 24),
        new HexCoordinates(2, 24),

        new HexCoordinates(-9, 25),
        new HexCoordinates(-8, 25),
        new HexCoordinates(-7, 25),
        new HexCoordinates(-6, 25),
        new HexCoordinates(-5, 25),
        new HexCoordinates(-4, 25),
        new HexCoordinates(-3, 25),
        new HexCoordinates(-2, 25),
        new HexCoordinates(-1, 25),
        new HexCoordinates(0, 25),
        new HexCoordinates(1, 25),
        new HexCoordinates(2, 25),
        new HexCoordinates(3, 25),
        new HexCoordinates(4, 25),
        new HexCoordinates(5, 25),

        new HexCoordinates(-10, 26),
        new HexCoordinates(-9, 26),
        new HexCoordinates(-8, 26),
        new HexCoordinates(-7, 26),
        new HexCoordinates(-6, 26),
        new HexCoordinates(-5, 26),
        new HexCoordinates(-4, 26),
        new HexCoordinates(-3, 26),
        new HexCoordinates(-2, 26),
        new HexCoordinates(-1, 26),
        new HexCoordinates(0, 26),
        new HexCoordinates(1, 26),
        new HexCoordinates(2, 26),
        new HexCoordinates(3, 26),
        new HexCoordinates(4, 26),

        new HexCoordinates(-11, 27),
        new HexCoordinates(-10, 27),
        new HexCoordinates(-9, 27),
        new HexCoordinates(-8, 27),
        new HexCoordinates(-7, 27),
        new HexCoordinates(-6, 27),
        new HexCoordinates(-5, 27),
        new HexCoordinates(-4, 27),
        new HexCoordinates(-3, 27),
        new HexCoordinates(-2, 27),
        new HexCoordinates(-1, 27),
        new HexCoordinates(0, 27),
        new HexCoordinates(1, 27),
        new HexCoordinates(2, 27),
        new HexCoordinates(3, 27),
        new HexCoordinates(4, 27),
        new HexCoordinates(5, 27)
    };

    public HexCoordinates[] plainsCoords =
    {
        new HexCoordinates(0, 0),
        new HexCoordinates(1, 0),
        new HexCoordinates(2, 0),
        new HexCoordinates(3, 0),
        new HexCoordinates(4, 0),
        new HexCoordinates(5, 0),
        new HexCoordinates(6, 0),
        new HexCoordinates(17, 0),
        new HexCoordinates(18, 0),
        new HexCoordinates(19, 0),

        new HexCoordinates(0, 1),
        new HexCoordinates(1, 1),
        new HexCoordinates(2, 1),
        new HexCoordinates(3, 1),
        new HexCoordinates(4, 1),
        new HexCoordinates(5, 1),
        new HexCoordinates(6, 1),
        new HexCoordinates(17, 1),
        new HexCoordinates(18, 1),

        new HexCoordinates(-1, 2),
        new HexCoordinates(0, 2),
        new HexCoordinates(1, 2),
        new HexCoordinates(2, 2),
        new HexCoordinates(3, 2),
        new HexCoordinates(4, 2),
        new HexCoordinates(5, 2),
        new HexCoordinates(6, 2),
        new HexCoordinates(16, 2),
        new HexCoordinates(17, 2),
        new HexCoordinates(18, 2),

        new HexCoordinates(-1, 3),
        new HexCoordinates(3, 3),
        new HexCoordinates(4, 3),
        new HexCoordinates(5, 3),
        new HexCoordinates(6, 3),
        new HexCoordinates(16, 3),
        new HexCoordinates(17, 3),

        new HexCoordinates(-2, 4),
        new HexCoordinates(-1, 4),
        new HexCoordinates(3, 4),
        new HexCoordinates(4, 4),
        new HexCoordinates(5, 4),
        new HexCoordinates(6, 4),
        new HexCoordinates(15, 4),
        new HexCoordinates(16, 4),
        new HexCoordinates(17, 4),

        new HexCoordinates(3, 5),
        new HexCoordinates(4, 5),
        new HexCoordinates(5, 5),
        new HexCoordinates(6, 5),
        new HexCoordinates(7, 5),
        new HexCoordinates(8, 5),
        new HexCoordinates(15, 5),
        new HexCoordinates(16, 5),

        new HexCoordinates(4, 6),
        new HexCoordinates(5, 6),
        new HexCoordinates(6, 6),
        new HexCoordinates(7, 6),
        new HexCoordinates(8, 6),
        new HexCoordinates(13, 6),
        new HexCoordinates(14, 6),
        new HexCoordinates(15, 6),
        new HexCoordinates(16, 6),

        new HexCoordinates(4, 7),
        new HexCoordinates(5, 7),
        new HexCoordinates(6, 7),
        new HexCoordinates(7, 7),
        new HexCoordinates(8, 7),
        new HexCoordinates(9, 7),
        new HexCoordinates(12, 7),
        new HexCoordinates(13, 7),
        new HexCoordinates(14, 7),
        new HexCoordinates(15, 7),

        new HexCoordinates(3, 8),
        new HexCoordinates(4, 8),
        new HexCoordinates(5, 8),
        new HexCoordinates(6, 8),
        new HexCoordinates(7, 8),
        new HexCoordinates(8, 8),
        new HexCoordinates(9, 8),
        new HexCoordinates(10, 8),
        new HexCoordinates(11, 8),
        new HexCoordinates(12, 8),
        new HexCoordinates(13, 8),
        new HexCoordinates(14, 8),
        new HexCoordinates(15, 8),

        new HexCoordinates(3, 9),
        new HexCoordinates(4, 9),
        new HexCoordinates(5, 9),
        new HexCoordinates(6, 9),
        new HexCoordinates(7, 9),
        new HexCoordinates(8, 9),
        new HexCoordinates(9, 9),
        new HexCoordinates(10, 9),
        new HexCoordinates(11, 9),
        new HexCoordinates(12, 9),
        new HexCoordinates(13, 9),

        new HexCoordinates(-5, 10),
        new HexCoordinates(-4, 10),
        new HexCoordinates(-3, 10),
        new HexCoordinates(-2, 10),
        new HexCoordinates(-1, 10),
        new HexCoordinates(2, 10),
        new HexCoordinates(3, 10),
        new HexCoordinates(4, 10),
        new HexCoordinates(5, 10),
        new HexCoordinates(6, 10),
        new HexCoordinates(7, 10),
        new HexCoordinates(9, 10),
        new HexCoordinates(10, 10),
        new HexCoordinates(11, 10),
        new HexCoordinates(12, 10),

        new HexCoordinates(-4, 11),
        new HexCoordinates(-3, 11),
        new HexCoordinates(-2, 11),
        new HexCoordinates(-1, 11),
        new HexCoordinates(0, 11),
        new HexCoordinates(3, 11),
        new HexCoordinates(4, 11),
        new HexCoordinates(5, 11),
        new HexCoordinates(6, 11),
        new HexCoordinates(7, 11),
        new HexCoordinates(8, 11),
        new HexCoordinates(9, 11),
        new HexCoordinates(10, 11),

        new HexCoordinates(-4, 12),
        new HexCoordinates(-3, 12),
        new HexCoordinates(-2, 12),
        new HexCoordinates(-1, 12),
        new HexCoordinates(0, 12),
        new HexCoordinates(4, 12),
        new HexCoordinates(5, 12),
        new HexCoordinates(6, 12),
        new HexCoordinates(7, 12),
        new HexCoordinates(8, 12),
        new HexCoordinates(9, 12),

        new HexCoordinates(-4, 13),
        new HexCoordinates(-3, 13),
        new HexCoordinates(5, 13),
        new HexCoordinates(6, 13),
        new HexCoordinates(7, 13),
        new HexCoordinates(8, 13),

        new HexCoordinates(-4, 14),
        new HexCoordinates(-3, 14),
        new HexCoordinates(-2, 14),
        new HexCoordinates(5, 14),
        new HexCoordinates(6, 14),
        new HexCoordinates(7, 14),
        new HexCoordinates(8, 14),

        new HexCoordinates(-5, 15),
        new HexCoordinates(-4, 15),
        new HexCoordinates(-3, 15),
        new HexCoordinates(-2, 15),
        new HexCoordinates(5, 15),
        new HexCoordinates(6, 15),
        new HexCoordinates(7, 15),
        new HexCoordinates(8, 15),
        new HexCoordinates(9, 15),
        new HexCoordinates(10, 15),

        new HexCoordinates(-5, 16),
        new HexCoordinates(-4, 16),
        new HexCoordinates(-3, 16),
        new HexCoordinates(-2, 16),
        new HexCoordinates(5, 16),
        new HexCoordinates(6, 16),
        new HexCoordinates(7, 16),
        new HexCoordinates(8, 16),
        new HexCoordinates(9, 16),
        new HexCoordinates(10, 16),

        new HexCoordinates(-6, 17),
        new HexCoordinates(-5, 17),
        new HexCoordinates(-4, 17),
        new HexCoordinates(-3, 17),
        new HexCoordinates(-2, 17),
        new HexCoordinates(4, 17),
        new HexCoordinates(5, 17),
        new HexCoordinates(6, 17),
        new HexCoordinates(7, 17),
        new HexCoordinates(8, 17),
        new HexCoordinates(9, 17),

        new HexCoordinates(-7, 18),
        new HexCoordinates(-6, 18),
        new HexCoordinates(-5, 18),
        new HexCoordinates(-4, 18),
        new HexCoordinates(-3, 18),
        new HexCoordinates(4, 18),
        new HexCoordinates(5, 18),
        new HexCoordinates(6, 18),
        new HexCoordinates(7, 18),
        new HexCoordinates(8, 18),
        new HexCoordinates(9, 18),

        new HexCoordinates(-8, 19),
        new HexCoordinates(-7, 19),
        new HexCoordinates(-6, 19),
        new HexCoordinates(-5, 19),
        new HexCoordinates(-4, 19),
        new HexCoordinates(-3, 19),
        new HexCoordinates(4, 19),
        new HexCoordinates(5, 19),
        new HexCoordinates(6, 19),
        new HexCoordinates(7, 19),
        new HexCoordinates(8, 19),
        new HexCoordinates(9, 19),

        new HexCoordinates(-8, 20),
        new HexCoordinates(-5, 20),
        new HexCoordinates(-4, 20),
        new HexCoordinates(3, 20),
        new HexCoordinates(5, 20),
        new HexCoordinates(6, 20),
        new HexCoordinates(7, 20),
        new HexCoordinates(8, 20),
        new HexCoordinates(9, 20),

        new HexCoordinates(-9, 21),
        new HexCoordinates(-8, 21),
        new HexCoordinates(3, 21),
        new HexCoordinates(5, 21),
        new HexCoordinates(6, 21),
        new HexCoordinates(7, 21),
        new HexCoordinates(8, 21),

        new HexCoordinates(-9, 22),
        new HexCoordinates(-8, 22),
        new HexCoordinates(4, 22),
        new HexCoordinates(5, 22),
        new HexCoordinates(6, 22),
        new HexCoordinates(7, 22),
        new HexCoordinates(8, 22),

        new HexCoordinates(-10, 23),
        new HexCoordinates(-9, 23),
        new HexCoordinates(-8, 23),
        new HexCoordinates(3, 23),
        new HexCoordinates(4, 23),
        new HexCoordinates(5, 23),
        new HexCoordinates(6, 23),
        new HexCoordinates(7, 23),

        new HexCoordinates(-10, 24),
        new HexCoordinates(-9, 24),
        new HexCoordinates(3, 24),
        new HexCoordinates(4, 24),
        new HexCoordinates(5, 24),
        new HexCoordinates(6, 24),
        new HexCoordinates(7, 24),

        new HexCoordinates(-11, 25),
        new HexCoordinates(-10, 25),
        new HexCoordinates(6, 25),

        new HexCoordinates(-12, 26),
        new HexCoordinates(-11, 26),
        new HexCoordinates(5, 26),
        new HexCoordinates(6, 26),

        new HexCoordinates(-12, 27)
    };

    public HexCoordinates[] forestCoords = 
    {
        new HexCoordinates(7, 0),
        new HexCoordinates(8, 0),
        new HexCoordinates(9, 0),
        new HexCoordinates(10, 0),
        new HexCoordinates(11, 0),
        new HexCoordinates(12, 0),
        new HexCoordinates(13, 0),
        new HexCoordinates(14, 0),
        new HexCoordinates(15, 0),
        new HexCoordinates(16, 0),

        new HexCoordinates(7, 1),
        new HexCoordinates(8, 1),
        new HexCoordinates(9, 1),
        new HexCoordinates(10, 1),
        new HexCoordinates(11, 1),
        new HexCoordinates(12, 1),
        new HexCoordinates(13, 1),
        new HexCoordinates(14, 1),
        new HexCoordinates(15, 1),
        new HexCoordinates(16, 1),

        new HexCoordinates(7, 2),
        new HexCoordinates(8, 2),
        new HexCoordinates(9, 2),
        new HexCoordinates(10, 2),
        new HexCoordinates(11, 2),
        new HexCoordinates(12, 2),
        new HexCoordinates(13, 2),
        new HexCoordinates(14, 2),
        new HexCoordinates(15, 2),

        new HexCoordinates(7, 3),
        new HexCoordinates(8, 3),
        new HexCoordinates(9, 3),
        new HexCoordinates(10, 3),
        new HexCoordinates(11, 3),
        new HexCoordinates(12, 3),
        new HexCoordinates(13, 3),
        new HexCoordinates(14, 3),
        new HexCoordinates(15, 3),

        new HexCoordinates(7, 4),
        new HexCoordinates(8, 4),
        new HexCoordinates(9, 4),
        new HexCoordinates(10, 4),
        new HexCoordinates(11, 4),
        new HexCoordinates(12, 4),
        new HexCoordinates(13, 4),
        new HexCoordinates(14, 4),

        new HexCoordinates(9, 5),
        new HexCoordinates(10, 5),
        new HexCoordinates(11, 5),
        new HexCoordinates(12, 5),
        new HexCoordinates(13, 5),
        new HexCoordinates(14, 5),

        new HexCoordinates(9, 6),
        new HexCoordinates(10, 6),
        new HexCoordinates(11, 6),
        new HexCoordinates(12, 6),

        new HexCoordinates(10, 7),
        new HexCoordinates(11, 7),

        new HexCoordinates(14, 9),

        new HexCoordinates(13, 10),
        new HexCoordinates(14, 10),

        new HexCoordinates(-5, 11),
        new HexCoordinates(11, 11),
        new HexCoordinates(12, 11),
        new HexCoordinates(13, 11),

        new HexCoordinates(-6, 12),
        new HexCoordinates(-5, 12),
        new HexCoordinates(10, 12),
        new HexCoordinates(11, 12),
        new HexCoordinates(12, 12),
        new HexCoordinates(13, 12),

        new HexCoordinates(-6, 13),
        new HexCoordinates(-5, 13),
        new HexCoordinates(9, 13),
        new HexCoordinates(10, 13),
        new HexCoordinates(11, 13),
        new HexCoordinates(12, 13),

        new HexCoordinates(-7, 14),
        new HexCoordinates(-6, 14),
        new HexCoordinates(-5, 14),
        new HexCoordinates(9, 14),
        new HexCoordinates(10, 14),
        new HexCoordinates(11, 14),
        new HexCoordinates(12, 14),

        new HexCoordinates(-7, 15),
        new HexCoordinates(-6, 15),
        new HexCoordinates(11, 15),

        new HexCoordinates(-8, 16),
        new HexCoordinates(-7, 16),
        new HexCoordinates(-6, 16),
        new HexCoordinates(11, 16),

        new HexCoordinates(-8, 17),
        new HexCoordinates(-7, 17),
        new HexCoordinates(10, 17),

        new HexCoordinates(-9, 18),
        new HexCoordinates(-8, 18),
        new HexCoordinates(10, 18),

        new HexCoordinates(-9, 19),

        new HexCoordinates(-10, 20),
        new HexCoordinates(-9, 20),

        new HexCoordinates(-10, 21),

        new HexCoordinates(-11, 22),
        new HexCoordinates(-10, 22),

        new HexCoordinates(-11, 23),

        new HexCoordinates(-12, 24),
        new HexCoordinates(-11, 24),

        new HexCoordinates(-12, 25),

        new HexCoordinates(-13, 26),

        new HexCoordinates(-13, 27),
    };

    public HexCoordinates[] impactSiteCoords =
    {
        new HexCoordinates(8, 10),
    };

    public HexCoordinates[] GetWaterCoords() { return waterCoords; }
    public HexCoordinates[] GetPlainsCoords() { return plainsCoords; }
    public HexCoordinates[] GetForestCoords() { return forestCoords; }
    public HexCoordinates[] GetInpactSiteCoords() { return impactSiteCoords; }
}